import { LE_OFFERINGS } from '@vritti/commerce-permissions/offerings';
import type { OfferingsBinding } from '@/components/offerings/bindings';
import {
  LE_OFFERING_VARIANTS_TABLE_KEY,
  LE_OFFERINGS_TABLE_KEY,
  useAddBomLine,
  useAddSuggestedComponent,
  useBulkSetOfferingsStatus,
  useBulkSetVariantsStatus,
  useClearVariantTaxClass,
  useCreateDimension,
  useCreateDimensionFromTemplate,
  useCreateOffering,
  useCreateVariant,
  useDeleteBomLine,
  useDeleteDimension,
  useDeleteOffering,
  useDeleteVariant,
  useGenerateVariants,
  useOffering,
  useOfferingDimensions,
  useOfferingsTable,
  useOfferingVariantsTable,
  usePreviewVariantCombinations,
  useReorderDimensions,
  useSetOfferingStatus,
  useSetOfferingTaxClass,
  useSetVariantTaxClass,
  useUpdateBomLine,
  useUpdateDimension,
  useUpdateOffering,
  useUpdateVariant,
  useUpsertDimensionValues,
  useVariant,
} from '@/hooks/legal-entity/offerings';

export const binding: OfferingsBinding = {
  permissions: LE_OFFERINGS,
  listDescription: 'Sellable products and their variants for this company',
  tableKey: LE_OFFERINGS_TABLE_KEY,
  tableSlug: 'commerce-le-offerings',
  variantsTableKey: LE_OFFERING_VARIANTS_TABLE_KEY,
  variantsTableSlug: (offeringId) => `commerce-le-offering-${offeringId}-variants`,

  useOfferingsTable,
  useOffering,
  useCreateOffering,
  useUpdateOffering,
  useDeleteOffering,
  useSetOfferingStatus,
  useBulkSetOfferingsStatus,

  useDimensions: useOfferingDimensions,
  useCreateDimension,
  useCreateDimensionFromTemplate,
  useUpsertDimensionValues,
  useUpdateDimension,
  useReorderDimensions,
  useDeleteDimension,

  useVariantsTable: useOfferingVariantsTable,
  useVariant,
  useCreateVariant,
  useGenerateVariants,
  usePreviewVariantCombinations,
  useUpdateVariant,
  useBulkSetVariantsStatus,
  useDeleteVariant,
  useSetOfferingTaxClass,
  useSetVariantTaxClass,
  useClearVariantTaxClass,
  useAddBomLine,
  useUpdateBomLine,
  useDeleteBomLine,
  useAddSuggestedComponent,
};
