ALTER POLICY "org_isolation" ON "vritti_core"."bom" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."bom" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."bom" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."bom" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."bom" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."categories" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."categories" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."categories" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."categories" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."categories" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."conversions" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."conversions" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."conversions" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."conversions" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."conversions" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."credit_notes" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."credit_notes" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."credit_notes" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."credit_notes" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."credit_notes" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."customers" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."customers" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."customers" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."customers" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."customers" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."document_counters" TO public USING ("vritti_core"."document_counters"."organization_id" = (select current_setting('app.org_id', true)::uuid)) WITH CHECK ("vritti_core"."document_counters"."organization_id" = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."goods_receipts" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."goods_receipts" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."goods_receipts" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."goods_receipts" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."goods_receipts" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."goods_receipt_items" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."goods_receipt_items" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."goods_receipt_items" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."goods_receipt_items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."goods_receipt_items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."goods_receipt_line_items" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."goods_receipt_line_items" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."goods_receipt_line_items" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."goods_receipt_line_items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."goods_receipt_line_items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."goods_receipt_lines" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."goods_receipt_lines" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."goods_receipt_lines" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."goods_receipt_lines" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."goods_receipt_lines" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."goods_receipt_lots" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."goods_receipt_lots" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."goods_receipt_lots" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."goods_receipt_lots" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."goods_receipt_lots" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."inventory_item_quant_items" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."inventory_item_quant_items" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."inventory_item_quant_items" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."inventory_item_quant_items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."inventory_item_quant_items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."inventory_item_lots" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."inventory_item_lots" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."inventory_item_lots" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."inventory_item_lots" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."inventory_item_lots" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."inventory_item_quants" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."inventory_item_quants" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."inventory_item_quants" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."inventory_item_quants" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."inventory_item_quants" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."inventory_items" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."inventory_items" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."inventory_items" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."inventory_items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."inventory_items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."invoices" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."invoices" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."invoices" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."invoices" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."invoices" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."item_field_definitions" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."item_field_definitions" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."item_field_definitions" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."item_field_definitions" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."item_field_definitions" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."items" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."items" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."items" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."modifier_groups" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."modifier_groups" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."modifier_groups" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."modifier_groups" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."modifier_groups" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."orders" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."orders" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."orders" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."orders" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."orders" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."price_list_items" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."price_list_items" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."price_list_items" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."price_list_items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."price_list_items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."price_lists" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."price_lists" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."price_lists" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."price_lists" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."price_lists" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."terminal_price_lists" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."terminal_price_lists" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."terminal_price_lists" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."terminal_price_lists" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."terminal_price_lists" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."pos_terminals" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."pos_terminals" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."pos_terminals" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."pos_terminals" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."pos_terminals" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."purchase_orders" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."purchase_orders" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."purchase_orders" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."purchase_orders" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."purchase_orders" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."stock_adjustment_line_items" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."stock_adjustment_line_items" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."stock_adjustment_line_items" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."stock_adjustment_line_items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."stock_adjustment_line_items" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."stock_adjustment_lines" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."stock_adjustment_lines" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."stock_adjustment_lines" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."stock_adjustment_lines" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."stock_adjustment_lines" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."stock_adjustment_lots" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."stock_adjustment_lots" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."stock_adjustment_lots" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."stock_adjustment_lots" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."stock_adjustment_lots" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."stock_adjustments" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."stock_adjustments" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."stock_adjustments" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."stock_adjustments" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."stock_adjustments" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."stock_transfers" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."storage_location_configs" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."storage_location_configs" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."storage_location_configs" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."storage_location_configs" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."storage_location_configs" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."storage_locations" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."storage_locations" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."storage_locations" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."storage_locations" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."storage_locations" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."supplier_contacts" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."supplier_contacts" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."supplier_contacts" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."supplier_contacts" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."supplier_contacts" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."suppliers" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."suppliers" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."suppliers" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."suppliers" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."suppliers" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."tax_groups" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."tax_groups" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."tax_groups" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."tax_groups" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."tax_groups" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."uom" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."uom" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."uom" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."uom" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."uom" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "org_isolation" ON "vritti_core"."uom_dimensions" TO public USING (organization_id = (select current_setting('app.org_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_ancestor_read" ON "vritti_core"."uom_dimensions" TO public USING (business_unit_id = ANY((select current_setting('app.bu_ancestor_ids', true))::uuid[]));--> statement-breakpoint
ALTER POLICY "bu_write" ON "vritti_core"."uom_dimensions" TO public WITH CHECK (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_update" ON "vritti_core"."uom_dimensions" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));--> statement-breakpoint
ALTER POLICY "bu_delete" ON "vritti_core"."uom_dimensions" TO public USING (business_unit_id = (select current_setting('app.bu_id', true)::uuid));