import { SITE_OFFERINGS } from '@vritti/commerce-permissions/offerings';
import type { OfferingsBinding } from '@/components/offerings/bindings';
import {
  SITE_OFFERING_VARIANTS_TABLE_KEY,
  SITE_OFFERINGS_TABLE_KEY,
  useAddBomLine,
  useAddSuggestedComponent,
  useBulkClearVariantsTaxClass,
  useBulkSetOfferingsStatus,
  useBulkSetVariantsAttribute,
  useBulkSetVariantsStatus,
  useBulkSetVariantsTaxClass,
  useClearVariantFulfilment,
  useClearVariantTaxClass,
  useCreateAttribute,
  useCreateAttributeFromTemplate,
  useCreateDimension,
  useCreateDimensionFromTemplate,
  useCreateOffering,
  useCreateVariant,
  useDeleteAttribute,
  useDeleteBomLine,
  useDeleteDimension,
  useDeleteOffering,
  useDeleteVariant,
  useGenerateVariants,
  useOffering,
  useOfferingAttributes,
  useOfferingDimensions,
  useOfferingsTable,
  useOfferingVariantsTable,
  usePreviewVariantCombinations,
  useReorderAttributes,
  useReorderDimensions,
  useSetOfferingFulfilment,
  useSetOfferingStatus,
  useSetOfferingTaxClass,
  useSetVariantAttributes,
  useSetVariantFulfilment,
  useSetVariantTaxClass,
  useUpdateAttribute,
  useUpdateBomLine,
  useUpdateDimension,
  useUpdateOffering,
  useUpdateVariant,
  useUpsertAttributeValues,
  useUpsertDimensionValues,
  useVariant,
  useVariantBom,
} from '@/hooks/site/offerings';

export const binding: OfferingsBinding = {
  permissions: SITE_OFFERINGS,
  listDescription: 'Sellable products and their variants for this outlet',
  tableKey: SITE_OFFERINGS_TABLE_KEY,
  tableSlug: 'commerce-site-offerings',
  variantsTableKey: SITE_OFFERING_VARIANTS_TABLE_KEY,
  variantsTableSlug: (offeringId) => `commerce-site-offering-${offeringId}-variants`,
  exportEndpoint: 'commerce-api/site/offerings/export',
  variantsExportEndpoint: (offeringId) => `commerce-api/site/offerings/${offeringId}/variants/export`,

  useOfferingsTable,
  useOffering,
  useCreateOffering,
  useUpdateOffering,
  useDeleteOffering,
  useSetOfferingStatus,
  useBulkSetOfferingsStatus,

  useAttributes: useOfferingAttributes,
  useCreateAttribute,
  useCreateAttributeFromTemplate,
  useUpsertAttributeValues,
  useUpdateAttribute,
  useReorderAttributes,
  useDeleteAttribute,
  useSetVariantAttributes,
  useBulkSetVariantsAttribute,

  useDimensions: useOfferingDimensions,
  useCreateDimension,
  useCreateDimensionFromTemplate,
  useUpsertDimensionValues,
  useUpdateDimension,
  useReorderDimensions,
  useDeleteDimension,

  useVariantsTable: useOfferingVariantsTable,
  useVariant,
  useVariantBom,
  useCreateVariant,
  useGenerateVariants,
  usePreviewVariantCombinations,
  useUpdateVariant,
  useBulkSetVariantsStatus,
  useBulkClearVariantsTaxClass,
  useBulkSetVariantsTaxClass,
  useDeleteVariant,
  useSetOfferingFulfilment,
  useSetOfferingTaxClass,
  useSetVariantFulfilment,
  useSetVariantTaxClass,
  useClearVariantFulfilment,
  useClearVariantTaxClass,
  useAddBomLine,
  useUpdateBomLine,
  useDeleteBomLine,
  useAddSuggestedComponent,
};
