import { SITE_OFFERINGS } from '@vritti/commerce-permissions/offerings';
import type { OfferingsBinding } from '@/components/offerings/bindings';
import {
  SITE_OFFERING_VARIANTS_TABLE_KEY,
  SITE_OFFERINGS_TABLE_KEY,
  useAddBomLine,
  useAddSuggestedComponent,
  useBulkSetOfferingsStatus,
  useBulkSetVariantsStatus,
  useClearVariantTaxClass,
  useCreateDimension,
  useCreateDimensionFromTemplate,
  useCreateOffering,
  useCreateVariant,
  useDeleteBomLine,
  useDeleteDimension,
  useDeleteOffering,
  useDeleteVariant,
  useGenerateVariants,
  useOffering,
  useOfferingDimensions,
  useOfferingsTable,
  useOfferingVariantsTable,
  usePreviewVariantCombinations,
  useReorderDimensions,
  useSetOfferingStatus,
  useSetOfferingTaxClass,
  useSetVariantTaxClass,
  useUpdateBomLine,
  useUpdateDimension,
  useUpdateOffering,
  useUpdateVariant,
  useUpsertDimensionValues,
  useVariant,
} from '@/hooks/site/offerings';

export const binding: OfferingsBinding = {
  permissions: SITE_OFFERINGS,
  listDescription: 'Sellable products and their variants for this outlet',
  tableKey: SITE_OFFERINGS_TABLE_KEY,
  tableSlug: 'commerce-site-offerings',
  variantsTableKey: SITE_OFFERING_VARIANTS_TABLE_KEY,
  variantsTableSlug: (offeringId) => `commerce-site-offering-${offeringId}-variants`,

  useOfferingsTable,
  useOffering,
  useCreateOffering,
  useUpdateOffering,
  useDeleteOffering,
  useSetOfferingStatus,
  useBulkSetOfferingsStatus,

  useDimensions: useOfferingDimensions,
  useCreateDimension,
  useCreateDimensionFromTemplate,
  useUpsertDimensionValues,
  useUpdateDimension,
  useReorderDimensions,
  useDeleteDimension,

  useVariantsTable: useOfferingVariantsTable,
  useVariant,
  useCreateVariant,
  useGenerateVariants,
  usePreviewVariantCombinations,
  useUpdateVariant,
  useBulkSetVariantsStatus,
  useDeleteVariant,
  useSetOfferingTaxClass,
  useSetVariantTaxClass,
  useClearVariantTaxClass,
  useAddBomLine,
  useUpdateBomLine,
  useDeleteBomLine,
  useAddSuggestedComponent,
};
