import { ORG_OFFERINGS } from '@vritti/commerce-permissions/offerings';
import type { OfferingsBinding } from '@/components/offerings/bindings';
import {
  ORG_OFFERING_VARIANTS_TABLE_KEY,
  ORG_OFFERINGS_TABLE_KEY,
  useAddBomLine,
  useAddSuggestedComponent,
  useBulkSetOfferingsStatus,
  useBulkSetVariantsStatus,
  useClearVariantTaxClass,
  useCreateDimension,
  useCreateDimensionFromTemplate,
  useCreateOffering,
  useCreateVariant,
  useCreateVariantInventoryItem,
  useDeleteBomLine,
  useDeleteDimension,
  useDeleteOffering,
  useDeleteVariant,
  useGenerateVariants,
  useOffering,
  useOfferingDimensions,
  useOfferingsTable,
  useOfferingVariantsTable,
  usePreviewVariantCombinations,
  useReorderDimensions,
  useSetOfferingStatus,
  useSetOfferingTaxClass,
  useSetVariantTaxClass,
  useUpdateBomLine,
  useUpdateDimension,
  useUpdateOffering,
  useUpdateVariant,
  useUpsertDimensionValues,
  useVariant,
} from '@/hooks/organization/offerings';

export const binding: OfferingsBinding = {
  permissions: ORG_OFFERINGS,
  listDescription: 'Sellable products and their variants',
  tableKey: ORG_OFFERINGS_TABLE_KEY,
  tableSlug: 'commerce-org-offerings',
  variantsTableKey: ORG_OFFERING_VARIANTS_TABLE_KEY,
  variantsTableSlug: (offeringId) => `commerce-org-offering-${offeringId}-variants`,

  useOfferingsTable,
  useOffering,
  useCreateOffering,
  useUpdateOffering,
  useDeleteOffering,
  useSetOfferingStatus,
  useBulkSetOfferingsStatus,

  useDimensions: useOfferingDimensions,
  useCreateDimension,
  useCreateDimensionFromTemplate,
  useUpsertDimensionValues,
  useUpdateDimension,
  useReorderDimensions,
  useDeleteDimension,

  useVariantsTable: useOfferingVariantsTable,
  useVariant,
  useCreateVariant,
  useGenerateVariants,
  usePreviewVariantCombinations,
  useUpdateVariant,
  useBulkSetVariantsStatus,
  useDeleteVariant,
  useSetOfferingTaxClass,
  useSetVariantTaxClass,
  useClearVariantTaxClass,
  useAddBomLine,
  useUpdateBomLine,
  useDeleteBomLine,
  useAddSuggestedComponent,
  useCreateVariantInventoryItem,
};
