packages:
  - apps/*
  - apps/micro-apps/*
  - apps/microservices/*
  - apps/web-mfs/*
  - libs/*
  - e2e/*

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@compodoc/compodoc'
  - '@nestjs/core'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - core-js
  - esbuild
  - nx
  - unrs-resolver

overrides:
  '@react-native-menu/menu': 2.0.0
  '@vritti/api-sdk': link:../api-sdk
  '@vritti/quantum-ui': link:../quantum-ui
  '@vritti/quantum-ui-native': link:../quantum-ui-native
  lightningcss: 1.30.1
  react-native-ios-context-menu: 3.2.1
  react-native-ios-utilities: 5.2.0

patchedDependencies:
  '@gorhom/bottom-sheet@5.2.13': patches/@gorhom__bottom-sheet@5.2.13.patch
  react-native-css@3.0.6: patches/react-native-css@3.0.6.patch
