import { ORG_PEOPLE } from '@vritti/commerce-permissions/people';
import {
  PERSON_ADDRESSES_TABLE_KEY,
  PERSON_BANK_ACCOUNTS_TABLE_KEY,
  PERSON_COMMUNICATIONS_TABLE_KEY,
  PERSON_IDENTIFIERS_KEY,
  PERSON_LICENSES_TABLE_KEY,
  PERSON_REGISTRATIONS_TABLE_KEY,
  PERSON_SOCIAL_PROFILES_TABLE_KEY,
  useAddPersonAddress,
  useAddPersonIdentifier,
  useCreatePersonBankAccount,
  useCreatePersonCommunication,
  useCreatePersonLicense,
  useCreatePersonRegistration,
  useCreatePersonSocialProfile,
  useDeletePersonBankAccount,
  useDeletePersonCommunication,
  useDeletePersonLicense,
  useDeletePersonRegistration,
  useDeletePersonSocialProfile,
  usePersonAddresses,
  usePersonBankAccountsTable,
  usePersonCommunicationsTable,
  usePersonIdentifiers,
  usePersonLicensesTable,
  usePersonRegistrationsTable,
  usePersonSocialProfilesTable,
  useRemovePersonAddress,
  useRemovePersonIdentifier,
  useUpdatePersonAddress,
  useUpdatePersonBankAccount,
  useUpdatePersonCommunication,
  useUpdatePersonLicense,
  useUpdatePersonRegistration,
  useUpdatePersonSocialProfile,
} from '@/hooks/organization/people';
import { PERSON_IDENTIFIER_TYPE_OPTIONS } from '@/schemas/party-identifiers';
import type {
  AddressesBinding,
  BankAccountsBinding,
  CommunicationsBinding,
  IdentifiersBinding,
  LicensesBinding,
  RegistrationsBinding,
  SocialProfilesBinding,
} from '../party/bindings';

export const personBindings: {
  identifiers: IdentifiersBinding;
  addresses: AddressesBinding;
  registrations: RegistrationsBinding;
  licenses: LicensesBinding;
  bankAccounts: BankAccountsBinding;
  communications: CommunicationsBinding;
  socialProfiles: SocialProfilesBinding;
} = {
  identifiers: {
    permissions: ORG_PEOPLE.identifiers,
    slug: (id) => `commerce-org-person-${id}-identifiers`,
    queryKey: PERSON_IDENTIFIERS_KEY,
    emptyDescription: "Record this person's identity documents like PAN, Aadhaar, or passport.",
    typeOptions: PERSON_IDENTIFIER_TYPE_OPTIONS,
    defaultType: 'PAN',
    valuePlaceholder: 'e.g. ABCDE1234F',
    useList: usePersonIdentifiers,
    useCreate: useAddPersonIdentifier,
    useRemove: useRemovePersonIdentifier,
  },
  addresses: {
    permissions: ORG_PEOPLE.addresses,
    slug: (id) => `commerce-org-person-${id}-addresses`,
    queryKey: PERSON_ADDRESSES_TABLE_KEY,
    emptyDescription: "Record this person's registered, billing, or shipping addresses.",
    useList: usePersonAddresses,
    useCreate: useAddPersonAddress,
    useUpdate: useUpdatePersonAddress,
    useRemove: useRemovePersonAddress,
  },
  registrations: {
    permissions: ORG_PEOPLE.registrations,
    slug: (id) => `commerce-org-person-${id}-registrations`,
    queryKey: PERSON_REGISTRATIONS_TABLE_KEY,
    emptyDescription: "Record this person's tax registration numbers per jurisdiction.",
    useList: usePersonRegistrationsTable,
    useCreate: useCreatePersonRegistration,
    useUpdate: useUpdatePersonRegistration,
    useRemove: useDeletePersonRegistration,
  },
  licenses: {
    permissions: ORG_PEOPLE.licenses,
    slug: (id) => `commerce-org-person-${id}-licenses`,
    queryKey: PERSON_LICENSES_TABLE_KEY,
    emptyDescription: 'Record regulatory licenses like drug, excise, or FSSAI for this person.',
    useList: usePersonLicensesTable,
    useCreate: useCreatePersonLicense,
    useUpdate: useUpdatePersonLicense,
    useRemove: useDeletePersonLicense,
  },
  bankAccounts: {
    permissions: ORG_PEOPLE.bankAccounts,
    slug: (id) => `commerce-org-person-${id}-bank-accounts`,
    queryKey: PERSON_BANK_ACCOUNTS_TABLE_KEY,
    emptyDescription: 'Record the bank accounts used to pay this person.',
    useList: usePersonBankAccountsTable,
    useCreate: useCreatePersonBankAccount,
    useUpdate: useUpdatePersonBankAccount,
    useRemove: useDeletePersonBankAccount,
  },
  communications: {
    permissions: ORG_PEOPLE.communications,
    slug: (id) => `commerce-org-person-${id}-communications`,
    queryKey: PERSON_COMMUNICATIONS_TABLE_KEY,
    emptyDescription: "Record this person's email addresses and phone numbers.",
    useList: usePersonCommunicationsTable,
    useCreate: useCreatePersonCommunication,
    useUpdate: useUpdatePersonCommunication,
    useRemove: useDeletePersonCommunication,
  },
  socialProfiles: {
    permissions: ORG_PEOPLE.socialProfiles,
    slug: (id) => `commerce-org-person-${id}-social-profiles`,
    queryKey: PERSON_SOCIAL_PROFILES_TABLE_KEY,
    emptyDescription: "Record this person's social and web profiles.",
    useList: usePersonSocialProfilesTable,
    useCreate: useCreatePersonSocialProfile,
    useUpdate: useUpdatePersonSocialProfile,
    useRemove: useDeletePersonSocialProfile,
  },
};
