DROP INDEX IF EXISTS vritti_core.idx_sa_line_items_adjustment;
DROP INDEX IF EXISTS vritti_core.idx_sa_line_items_item;

ALTER TABLE vritti_core.stock_adjustment_line_items
DROP CONSTRAINT IF EXISTS stock_adjustment_line_items_stock_adjustment_id_stock_adjustments_id_fk;

ALTER TABLE vritti_core.stock_adjustment_line_items
DROP CONSTRAINT IF EXISTS stock_adjustment_line_items_inventory_item_id_inventory_items_id_fk;

ALTER TABLE vritti_core.stock_adjustment_line_items
DROP COLUMN IF EXISTS stock_adjustment_id;

ALTER TABLE vritti_core.stock_adjustment_line_items
DROP COLUMN IF EXISTS inventory_item_id;
