import { defineRelations } from '@vritti/api-sdk/drizzle-orm';
import * as schema from './index';

export const relations = defineRelations(schema, (_r) => ({
  categories: {},
  items: {},
  itemOptions: {},
  itemOptionValues: {},
  itemVariants: {},
  itemVariantOptionValues: {},
  modifierGroups: {},
  modifierOptions: {},
  itemModifierGroups: {},
  taxGroups: {},
  taxRates: {},
  itemFieldDefinitions: {},
  itemFieldValues: {},
  uom: {},
  inventoryItems: {},
  storageLocations: {},
  inventoryLevels: {},
  inventoryLedger: {},
  bom: {},
  bomLines: {},
  suppliers: {},
  supplierItems: {},
  purchaseOrders: {},
  purchaseOrderItems: {},
  goodsReceipts: {},
  goodsReceiptItems: {},
  conversions: {},
  conversionInputs: {},
  conversionOutputs: {},
  stockAdjustments: {},
  stockTransfers: {},
  invoices: {},
  invoiceItems: {},
  payments: {},
  creditNotes: {},
  creditNoteApplications: {},
  orders: {},
  orderItems: {},
  orderItemModifiers: {},
}));
