import type { CodegenConfig } from '@graphql-codegen/cli';

// graphql-codegen client-preset — generates typed `graphql()` documents (TypedDocumentNode) + types
// from core-server's code-first schema (regenerated by NestJS on boot/build). Operations are written
// with the generated `graphql()` (imported from `src/gql`) and consumed by Apollo v4
// useQuery/useMutation with full type inference. `fragmentMasking` is off for now — typed documents
// without the unmask ceremony. Run `pnpm codegen` (or `codegen:watch`) before typecheck/dev.
const config: CodegenConfig = {
  schema: '../../core-server/src/schema.gql',
  documents: ['src/**/*.{ts,tsx}', '!src/gql/**'],
  ignoreNoDocuments: true,
  generates: {
    'src/gql/': {
      preset: 'client',
      presetConfig: { fragmentMasking: false },
      config: { scalars: { DateTime: 'string' } },
    },
  },
};

export default config;
