import { ORG_COMPANIES } from '@vritti/commerce-permissions/companies';
import {
  COMPANY_ADDRESSES_TABLE_KEY,
  COMPANY_BANK_ACCOUNTS_TABLE_KEY,
  COMPANY_COMMUNICATIONS_TABLE_KEY,
  COMPANY_IDENTIFIERS_TABLE_KEY,
  COMPANY_LICENSES_TABLE_KEY,
  COMPANY_REGISTRATIONS_TABLE_KEY,
  COMPANY_SOCIAL_PROFILES_TABLE_KEY,
  useAddCompanyAddress,
  useAddCompanyIdentifier,
  useCompanyAddresses,
  useCompanyBankAccountsTable,
  useCompanyCommunicationsTable,
  useCompanyIdentifiers,
  useCompanyLicensesTable,
  useCompanyRegistrationsTable,
  useCompanySocialProfilesTable,
  useCreateCompanyBankAccount,
  useCreateCompanyCommunication,
  useCreateCompanyLicense,
  useCreateCompanyRegistration,
  useCreateCompanySocialProfile,
  useDeleteCompanyBankAccount,
  useDeleteCompanyCommunication,
  useDeleteCompanyLicense,
  useDeleteCompanyRegistration,
  useDeleteCompanySocialProfile,
  useRemoveCompanyAddress,
  useRemoveCompanyIdentifier,
  useUpdateCompanyAddress,
  useUpdateCompanyBankAccount,
  useUpdateCompanyCommunication,
  useUpdateCompanyLicense,
  useUpdateCompanyRegistration,
  useUpdateCompanySocialProfile,
} from '@/hooks/organization/companies';
import { COMPANY_IDENTIFIER_TYPE_OPTIONS } from '@/schemas/party-identifiers';
import type {
  AddressesBinding,
  BankAccountsBinding,
  CommunicationsBinding,
  IdentifiersBinding,
  LicensesBinding,
  RegistrationsBinding,
  SocialProfilesBinding,
} from '../party/bindings';

export const companyBindings: {
  identifiers: IdentifiersBinding;
  addresses: AddressesBinding;
  registrations: RegistrationsBinding;
  licenses: LicensesBinding;
  bankAccounts: BankAccountsBinding;
  communications: CommunicationsBinding;
  socialProfiles: SocialProfilesBinding;
} = {
  identifiers: {
    permissions: ORG_COMPANIES.identifiers,
    slug: (id) => `commerce-org-company-${id}-identifiers`,
    queryKey: COMPANY_IDENTIFIERS_TABLE_KEY,
    emptyDescription: "Record this company's identifiers like CIN, LEI, or DUNS.",
    typeOptions: COMPANY_IDENTIFIER_TYPE_OPTIONS,
    defaultType: 'CIN',
    valuePlaceholder: 'e.g. U74999KA2020PTC000000',
    useList: useCompanyIdentifiers,
    useCreate: useAddCompanyIdentifier,
    useRemove: useRemoveCompanyIdentifier,
  },
  addresses: {
    permissions: ORG_COMPANIES.addresses,
    slug: (id) => `commerce-org-company-${id}-addresses`,
    queryKey: COMPANY_ADDRESSES_TABLE_KEY,
    emptyDescription: "Record this company's registered, billing, or shipping addresses.",
    useList: useCompanyAddresses,
    useCreate: useAddCompanyAddress,
    useUpdate: useUpdateCompanyAddress,
    useRemove: useRemoveCompanyAddress,
  },
  registrations: {
    permissions: ORG_COMPANIES.registrations,
    slug: (id) => `commerce-org-company-${id}-registrations`,
    queryKey: COMPANY_REGISTRATIONS_TABLE_KEY,
    emptyDescription: "Record this company's tax registration numbers per jurisdiction.",
    useList: useCompanyRegistrationsTable,
    useCreate: useCreateCompanyRegistration,
    useUpdate: useUpdateCompanyRegistration,
    useRemove: useDeleteCompanyRegistration,
  },
  licenses: {
    permissions: ORG_COMPANIES.licenses,
    slug: (id) => `commerce-org-company-${id}-licenses`,
    queryKey: COMPANY_LICENSES_TABLE_KEY,
    emptyDescription: 'Record regulatory licenses like drug, excise, or FSSAI for this company.',
    useList: useCompanyLicensesTable,
    useCreate: useCreateCompanyLicense,
    useUpdate: useUpdateCompanyLicense,
    useRemove: useDeleteCompanyLicense,
  },
  bankAccounts: {
    permissions: ORG_COMPANIES.bankAccounts,
    slug: (id) => `commerce-org-company-${id}-bank-accounts`,
    queryKey: COMPANY_BANK_ACCOUNTS_TABLE_KEY,
    emptyDescription: 'Record the bank accounts used to pay this company.',
    useList: useCompanyBankAccountsTable,
    useCreate: useCreateCompanyBankAccount,
    useUpdate: useUpdateCompanyBankAccount,
    useRemove: useDeleteCompanyBankAccount,
  },
  communications: {
    permissions: ORG_COMPANIES.communications,
    slug: (id) => `commerce-org-company-${id}-communications`,
    queryKey: COMPANY_COMMUNICATIONS_TABLE_KEY,
    emptyDescription: "Record this company's email addresses and phone numbers.",
    useList: useCompanyCommunicationsTable,
    useCreate: useCreateCompanyCommunication,
    useUpdate: useUpdateCompanyCommunication,
    useRemove: useDeleteCompanyCommunication,
  },
  socialProfiles: {
    permissions: ORG_COMPANIES.socialProfiles,
    slug: (id) => `commerce-org-company-${id}-social-profiles`,
    queryKey: COMPANY_SOCIAL_PROFILES_TABLE_KEY,
    emptyDescription: "Record this company's social and web profiles.",
    useList: useCompanySocialProfilesTable,
    useCreate: useCreateCompanySocialProfile,
    useUpdate: useUpdateCompanySocialProfile,
    useRemove: useDeleteCompanySocialProfile,
  },
};
