import type { CodegenConfig } from '@graphql-codegen/cli';

// Emits TypeScript types for the core-server code-first schema (scalars, object/input/enum types)
// and validates the app's GraphQL operations against it on load. Hooks consume operations via
// `gql` + explicit generics today.
//
// Apollo Client v4 / codegen notes (do NOT regress these):
// - Do NOT use `typescript-react-apollo` — it emits v3-era helper types (QueryResult,
//   MutationFunction, MutationResult, BaseMutationOptions) that were renamed/removed in v4.
// - Do NOT add `typescript-operations` alongside `typescript` in this output — in this codegen
//   version it re-emits input types, producing duplicate identifiers.
// - For fully-typed operations later, migrate to the graphql-codegen client-preset
//   (TypedDocumentNode) — the proper v4 path.
const config: CodegenConfig = {
  // The INTERNAL schema (regenerated by NestJS on boot/build). core-server serves two GraphQL
  // surfaces: /graphql (storefront, public, schema.app.gql) and /mobile-graphql (this one).
  schema: '../core-server/src/schema.mobile.gql',
  // Operation documents live alongside the host source (the generated dir is excluded).
  documents: ['src/host/**/*.{ts,tsx,graphql}', '!src/host/graphql/generated/**'],
  ignoreNoDocuments: true,
  config: {
    scalars: { DateTime: 'string' },
  },
  generates: {
    'src/host/graphql/generated/graphql.ts': {
      plugins: ['typescript'],
    },
  },
};

export default config;
