/*
 * Generated by `pnpm generate:importmap` — do not edit.
 *
 * Ships empty because generating it needs the resolved dependency tree, which a
 * scaffold does not have yet. **Run `pnpm generate:importmap` before opening
 * /admin**, or every component a plugin registers fails to resolve and the panel
 * renders "PayloadComponent not found in importMap".
 *
 * Re-run it whenever a plugin is added or removed, or a custom admin component
 * is registered. The file is committed, like the sibling sites commit theirs.
 */
export const importMap = {}
